### ISSUE TITLE
oe_media_webtools_post_update_00005() ERROR on openeuropa/oe_media upgrade to v1.19

### ISSUE THREAD

**Issue by serotonine** [openeuropa/oe_media#204]
```
 oe_media_webtools   00005       post-update   Update Webtools media fields  
                                                description to include the    
                                                WCLOUD wizard link.           
 ------------------- ----------- ------------- ------------------------------ 

>  [notice] Update started: oe_media_webtools_post_update_00005
> Error: Call to a member function get() on null in ./web/modules/contrib/oe_media/modules/oe_media_webtools/oe_media_webtools.post_update.php on line 108 #0 ./vendor/drush/drush/src/Commands/core/UpdateDBCommands.php(321): oe_media_webtools_post_update_00005()
```

**Comment by miguelst** [comment]
Hello,

I have also the same error updating openeuropa/oe_media from version 1.18 to 1.19:

```
 ------------------- ----------- ------------- ------------------------------ 
  Module              Update ID   Type          Description                   
 ------------------- ----------- ------------- ------------------------------ 
  oe_authentication   00002       post-update   Update email domain in CAS    
                                                settings.                     
  oe_authentication   00003       post-update   Set force_2fa to FALSE as     
                                                default.                      
  oe_media_webtools   00005       post-update   Update Webtools media fields  
                                                description to include the    
                                                WCLOUD wizard link.           
 ------------------- ----------- ------------- ------------------------------ 

 Do you wish to run the specified pending updates? (yes/no) [yes]:
 > y
>  [notice] Update started: oe_authentication_post_update_00002
>  [notice] Update completed: oe_authentication_post_update_00002
>  [notice] Update started: oe_authentication_post_update_00003
>  [notice] Update completed: oe_authentication_post_update_00003
>  [notice] Update started: oe_media_webtools_post_update_00005
> Error: Call to a member function get() on null in /home/ec2-user/environment/ewrc-oe12/web/modules/contrib/oe_media/modules/oe_media_webtools/oe_media_webtools.post_update.php on line 108 #0 /home/ec2-user/environment/ewrc-oe12/vendor/drush/drush/src/Commands/core/UpdateDBCommands.php(321): oe_media_webtools_post_update_00005()
> #1 /home/ec2-user/environment/ewrc-oe12/vendor/drush/drush/includes/batch.inc(261): Drush\Commands\core\UpdateDBCommands::updateDoOnePostUpdate()
> #2 /home/ec2-user/environment/ewrc-oe12/vendor/drush/drush/includes/batch.inc(206): _drush_batch_worker()
> #3 /home/ec2-user/environment/ewrc-oe12/vendor/drush/drush/includes/batch.inc(100): _drush_batch_command()
> #4 /home/ec2-user/environment/ewrc-oe12/vendor/drush/drush/src/Commands/core/UpdateDBCommands.php(175): drush_batch_command()
> #5 [internal function]: Drush\Commands\core\UpdateDBCommands->process()
> #6 /home/ec2-user/environment/ewrc-oe12/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array()
> #7 /home/ec2-user/environment/ewrc-oe12/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback()
> #8 /home/ec2-user/environment/ewrc-oe12/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter()
> #9 /home/ec2-user/environment/ewrc-oe12/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(350): Consolidation\AnnotatedCommand\CommandProcessor->process()
> #10 /home/ec2-user/environment/ewrc-oe12/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute()
> #11 /home/ec2-user/environment/ewrc-oe12/vendor/symfony/console/Application.php(1027): Symfony\Component\Console\Command\Command->run()
> #12 /home/ec2-user/environment/ewrc-oe12/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
> #13 /home/ec2-user/environment/ewrc-oe12/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
> #14 /home/ec2-user/environment/ewrc-oe12/vendor/drush/drush/src/Runtime/Runtime.php(118): Symfony\Component\Console\Application->run()
> #15 /home/ec2-user/environment/ewrc-oe12/vendor/drush/drush/src/Runtime/Runtime.php(48): Drush\Runtime\Runtime->doRun()
> #16 /home/ec2-user/environment/ewrc-oe12/vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run()
> #17 /home/ec2-user/environment/ewrc-oe12/vendor/drush/drush/drush(3): require('/home/ec2-user/...')
> #18 /home/ec2-user/environment/ewrc-oe12/vendor/bin/drush(115): include('/home/ec2-user/...')
> #19 {main}
>  [warning] Drush command terminated abnormally.
In ProcessBase.php line 171:
  Unable to decode output into JSON: Syntax error                               Error: Call to a member function get() on null in oe_media_webtools_post_update_00005() (line 108 of /home/ec2-user/environment/ewrc-oe12/web/modules/contrib/oe_media/modules/oe_me  
  dia_webtools/oe_media_webtools.post_update.php).
```

Could you please look into it?

Thanks in advance,

Miguel
